#define BMPHEIGHT_mpegplayer_status_icons_8x8x1 8
#define BMPWIDTH_mpegplayer_status_icons_8x8x1 40
extern const unsigned char mpegplayer_status_icons_8x8x1[];
extern const struct bitmap bm_mpegplayer_status_icons_8x8x1;
