/* Generated by convbdf on Mon Apr 21 02:45:08 2014. */
#ifdef HAVE_LCD_BITMAP

/* Font information */
#define SYSFONT_NAME           08-Schumacher-Clean
#define SYSFONT_FACENAME       -Schumacher-Clean-Medium-R-Normal--8-80-75-75-C-60-ISO10646-1
#define SYSFONT_WIDTH          6
#define SYSFONT_HEIGHT         8
#define SYSFONT_SIZE           256
#define SYSFONT_ASCENT         7
#define SYSFONT_DEPTH          0
#define SYSFONT_DESCENT        1
#define SYSFONT_FIRST_CHAR     0
#define SYSFONT_LAST_CHAR      255
#define SYSFONT_DEFAULT_CHAR   0
#define SYSFONT_PROPORTIONAL   0
#define SYSFONT_COPYRIGHT      Copyright 1989 Dale Schumacher.
#define SYSFONT_BITS_SIZE      1146

#endif
